### ISSUE TITLE
ReadMe out of date

### ISSUE THREAD

**Issue by mmclane** [inspec/inspec-azure#114]
### 🎛 Description
The README seems to be about of date in reference to the rake commands.
  
🐛 bug report

The rake commands seem to have changed.  For instance, when I run rake --tasks I get the following:
{16:12 - m.mclane@C02TG0YSHF1R}~/Repos/inspec-azure:subnets ✗  ➭ rake --tasks
rake attributes:write             # Create attributes used for integration testing
rake azure                        # Set up Azure env, run integration tests, destroy Azure env
rake azure:login                  # Authenticate with the Azure CLI
rake docs:resource_links          # Prints markdown links for resource doc files to update the README
rake inspec:check                 # InSpec syntax check
rake inspec:run[subscription_id]  # Runs profile against Azure with given Subscription Id
rake lint                         # Linting tasks
rake options[component]           # Enables given optional components
rake rubocop                      # Run RuboCop
rake rubocop:auto_correct         # Auto-correct RuboCop offenses
rake syntax                       # Ruby syntax check
rake test                         # Testing tasks
rake test:unit                    # Run tests for unit
rake tf:apply                     # Executes the Terraform plan
rake tf:destroy                   # Destroys the Terraform environment
rake tf:plan                      # Creates a Terraform execution plan from the plan file

But the README references rake test:integration.  That doesn't seem to be an option anymore.

**Comment by dmccown** [comment]
That task doesn't show up in the task list because we don't have a description on it. You can see the task is defined here: https://github.com/inspec/inspec-azure/blob/master/Rakefile#L142. We can update the task to add a description so it will show up in the task list.

Thanks!

**Comment by mmclane** [comment]
I get an error when I run that command.

{12:59 - m.mclane@C02TG0YSHF1R}~/Repos/inspec-azure:subnets ✗  ➭ rake integration:test
rake aborted!
Don't know how to build task 'integration:test' (see --tasks)
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
{12:59 - m.mclane@C02TG0YSHF1R}~/Repos/inspec-azure:subnets ✗  ➭

**Comment by mmclane** [comment]
OK.. my bad.. I was typing it in backwards (rake integration:test).
It does run when I use rake test:integration.  

I can't however run a specific control.

 ➭ rake test:integration[azurerm_virtual_machine]
zsh: no matches found: test:integration[azurerm_virtual_machine]

**Comment by dmccown** [comment]
Oh that's a quirky zsh issue. I'm not sure why mine works, but you'll need to put the args in quotes.

```
rake "test:integration[azurerm_virtual_machine]"
```

Someone on our side had the same issue.

**Comment by dmccown** [comment]
Here's a post describing your issue and how to work around it: http://mikeballou.com/blog/2011/07/18/zsh-and-rake-parameters/

**Comment by mmclane** [comment]
Yep, your right.

**Comment by mmclane** [comment]
Yep, your right.
