### ISSUE TITLE
Revisit response caching strategy

### ISSUE THREAD

**Issue by TrevorBramble** [inspec/inspec-azure#147]
### 🎛 Description

Currently there is a single shared cache of response data per service backend. For backends that connect to more than one domain (Vault, at least) this leads to cache collisions.

For more details: https://github.com/inspec/inspec-azure/pull/142#discussion_r224115166

### 💁 Possible Solutions

There may be a couple of approaches here, one might be including the service domain in the cache data somehow.
```ruby
{'x.example.com' => {'/some/path' => '{"some": "data"}'}}
# or
{'x.example.com/some/path' => '{"some": "data"}'}
```
Another might be spawning separate instances of a service based on the given client. This might bend or break important parts of the current design, which is fine, if the results are worth it. (Abandoning the singleton implementation is almost certain in this scenario.)

**Comment by omerdemirok** [comment]
@TrevorBramble, can you confirm that this still an issue in the latest version of the [Azure resource pack](https://github.com/inspec/inspec-azure)?

**Comment by TrevorBramble** [comment]
@omerdemirok I've never used this outside of building it. No idea. Feel free to close if you think it's obsolete or satisfied.

**Comment by omerdemirok** [comment]
@TrevorBramble, thanks for the update.
I'm closing this for now, but feel free to reopen if you encounter the same issue.
