### ISSUE TITLE
Add resources to test EventHub Namespace, Event Hub, Authorization Rule and IoT Hub

### ISSUE THREAD

**Issue by MRushtonScratch** [inspec/inspec-azure#171]
### 🎛 Description

Feature Request, to add functionality for Azure resources to enable testing of 
- Event Hub Namespace - https://docs.microsoft.com/en-us/rest/api/eventhub/namespaces/get
- Event Hub Event Hub - https://docs.microsoft.com/en-us/rest/api/eventhub/eventhubs/get
- Event Hub Authorization Rule - https://docs.microsoft.com/en-us/rest/api/eventhub/eventhubs/getauthorizationrule
- IoT Hub - https://docs.microsoft.com/en-us/rest/api/iothub/iothubresource/get
- IoT Hub Consumer Group - https://docs.microsoft.com/en-us/rest/api/iothub/iothubresource/geteventhubconsumergroup
- IoT Hub Consumer Groups - https://docs.microsoft.com/en-us/rest/api/iothub/iothubresource/listeventhubconsumergroups

**Comment by rmoles** [comment]
This has been covered by #175
