### ISSUE TITLE
Add resource to test Cosmos Db Account

### ISSUE THREAD

**Issue by MRushtonScratch** [inspec/inspec-azure#174]
### 🎛 Description

Feature Request, to add functionality for Azure resources to enable testing of 
- Cosmos Db Account - https://docs.microsoft.com/en-us/rest/api/cosmos-db-resource-provider/databaseaccounts/get#definitions

**Comment by doc82** [comment]
is there a way to do this with a generic resource?

**Comment by rmoles** [comment]
This has been covered by #175
