### ISSUE TITLE
User Managed identity VM extension deprecated, support managed identity metadata service

### ISSUE THREAD

**Issue by cwebbtw** [inspec/inspec-azure#185]
Support user managed identities using the azure instance metadata service rather than the deprecated VM extension. 

## Detailed Description
This change would support user managed identities without needing to use a deprecated extension whilst moving towards a model where client id and secret aren't required. 

Not currently sure if a workaround is possible by supplying the access token as the secret id parameter although I suspect a code change required. 

## Possible Implementation
Instead of calling the vm extension port, obtain the access token from the instance metadata service.

**Comment by omerdemirok** [comment]
Hi @cwebbtw, can you elaborate the issue? Which extension port do you refer here: `Instead of calling the vm extension port, obtain the access token from the instance metadata service`?
It would be great if you can provide a link in this resource pack, so that we can be on the same page.

**Comment by omerdemirok** [comment]
@cwebbtw, I am closing this issue for now. 
Please feel free to re-open it if you think it is still relevant.
