### ISSUE TITLE
Inspec not able to validate azure app services 

### ISSUE THREAD

**Issue by balasundarbala** [inspec/inspec-azure#191]
How to validate azure app services {fucntion app ,web app} in inspec azure .I could not find any library for it in azure resource management

**Comment by avishnyakov** [comment]
By looking into source code, there are these resources:
* https://github.com/inspec/inspec-azure/blob/master/libraries/azurerm_webapp.rb
* https://github.com/inspec/inspec-azure/blob/master/libraries/azurerm_webapps.rb

I think they just have not been documented?

**Comment by r-fennell** [comment]
Added in https://github.com/inspec/inspec-azure/pull/217
