### ISSUE TITLE
Add support for Azure PostGreSQL server/DB test

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-azure#195]
@svangeti commented on [Tue Aug 20 2019](https://github.com/inspec/inspec/issues/4403)

## Detailed Description
There is no support for Azure Postgres server/databases testing.

## Context
We are currently planning to use InSpec for our Azure Infra testing

## Possible Implementation
If it uses terraform, we can use terraform provider 
azurerm_postgresql_server
azurerm_postgresql_database

**Comment by r-fennell** [comment]
Added in https://github.com/inspec/inspec-azure/pull/214
