### ISSUE TITLE
azure_generic_resource gives unreliable results

### ISSUE THREAD

**Issue by mmclane** [inspec/inspec-azure#204]
### 🎛 I believe this resource is evaluating properties of the resource group and returning a false positive when your trying to evaluate a resource within that group.   

is this a 🐛 bug report

Briefly describe the issue and the expected behavior

### 🌍 InSpec and Platform Version
inspec version 2.1.83 on OSX 10.13.4

### 🤔 Replication Case
```
control 'foobar' do
  title 'foobar'
  describe azure_generic_resource(group_name: '<existing resource group>, name: 'foobar') do
    it { should exist }
    its('location') { should cmp 'eastus' }
    its('provisioning_state') { should cmp 'Succeeded' }

    its('properties.addressSpace.addressPrefixes') { should cmp '10.6.8.0/22' }
    its('properties.dhcpOptions.dnsServers') { should cmp ["10.6.8.4", "168.63.129.16"] }
    it { should have_tags }
    its ('Environment_tag') { should cmp 'prod'}
    its ('ManagedBy_tag') { should cmp 'Terraform'}
    its ('Project_tag') { should cmp 'infra'}
  end
end
```
foobar: foobar (2 failed)
     ✔  azure_generic_resource should exist
     ✔  azure_generic_resource should have tags
     ✔  azure_generic_resource location should cmp == "eastus"
     ✔  azure_generic_resource provisioning_state should cmp == "Succeeded"
     ×  azure_generic_resource properties.addressSpace.addressPrefixes
     undefined method `addressSpace' for []:Array
     ×  azure_generic_resource properties.dhcpOptions.dnsServers
     undefined method `dhcpOptions' for []:Array
     ✔  azure_generic_resource Environment_tag should cmp == "prod"
     ✔  azure_generic_resource ManagedBy_tag should cmp == "Terraform"
     ✔  azure_generic_resource Project_tag should cmp == "infra"

Since the resource foobar doesn't exist in the resource group, all of those tests should fail, but only the two referencing the specific properties fail.

The documentation here: https://www.inspec.io/docs/reference/resources/azure_generic_resource/ at says that the tag and location tests should at least be usable but both return as successful even when the resource doesn't exist.

### 💁 Possible Solutions

I currently don't know of a solution other then to no use those tests, but in that case this becomes a lot more restrictive, and prone to false positives, and the documentation should be updated to reflect this.

**Comment by anniehedgpeth** [comment]
I'd like to echo the question. If we can't audit _every_ resource in Azure, then using InSpec for validating Azure deployments becomes less attractive. And it seems unlikely that inspec-azure would be able to keep up with every new resource created, so the `azurerm_generic_resource` seems extremely necessary, so much so that I don't even know if I could continue to recommend it for Azure validations anymore.

**Comment by avishnyakov** [comment]
@anniehedgpeth I gave up, here is how this problem can be approached:

* use `az cli` to dump JSON output from needed resources
* if `az cli` does not support what you need, use REST API to dump json
* if needed, enhance JSON with additional data (so you can link different JSON arrays)

Now, use InSpec JSON data source with no additional dependencies, simply validate JSON which you fetched from Azure by az cli or other means. You still can wrap JSON into resources if you need to or wrap custom functions to simplify assertions.

Super-simple, no dependencies, no bugs, no wait on GitHub issues here and there.
This approach also provides consistency for other systems you would need to validate. Most of the time, you would be able to get JSON dump from REST APIs of the target system.

**Comment by anniehedgpeth** [comment]
That's great, @avishnyakov , thanks for sharing!

**Comment by Sum123it** [comment]
Yes, @avishnyakov. Looks like it's a dead-end without azure_generic_resources. I understand this even though I am new to this. Looks like dumped JSON is the option now.

**Comment by rmoles** [comment]
Hi folks 👋 
We endeavor to update the cloud resource packs as often as possible. Are there any specific examples of functionality you require that are missing from the resource pack today? 
If so I would kindly ask that issues be raised in the corresponding cloud resource pack repo, so we can track and implement the functionality required in the community.
PRs are also more than welcome from the community. We will do our best to get any PRs reviewed and merged ASAP.
https://github.com/inspec/inspec-aws
https://github.com/inspec/inspec-gcp
https://github.com/inspec/inspec-azure

**Comment by Schwad** [comment]
As `azure_generic_resource` has been deprecated a while (and we are working hard to clear out as many deprecations as we can with the next InSpec major version) @mmclane would you be comfortable closing this issue?

Or are there other issues that we need to address, perhaps in a newer issue? 

https://github.com/inspec/inspec/pull/3132

**Comment by omerdemirok** [comment]
@Sum123it, @Schwad, @clintoncwolfe, @anniehedgpeth, @mmclane: `azure_generic_resource` [singular](https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_generic_resource.md) and `azure_generic_resources` [plural](https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_generic_resources.md) resources are available again with a complete rewrite. 
Please see the project [readme](https://github.com/inspec/inspec-azure/blob/master/README.md) and resource docs on how to use them, and update this ticket with your experience.

Note: Remember to use the latest version of the resource pack in the `inspec.yml` and delete existing `inspec.lock` file in your profile.

**Comment by tbugfinder** [comment]
Hi,
due to lack of available support of resources in inspect-azure we've built lot of ruby code to verify resources. Yet this code isn't building InSpec resources, though.

**Comment by tbugfinder** [comment]
Definitely we'll look into the new generic resource definitions !

**Comment by omerdemirok** [comment]
Please feel free to re-open this issue if the same problems occur.
