### ISSUE TITLE
Train Plugin Azure - Not Found

### ISSUE THREAD

**Issue by phenggeler** [inspec/inspec-azure#234]
I have inspec running in a pipeline to test changes. Suddenly today, we are started seeing the following error when we tried to run Inspec:

"Can't find train plugin azure. Please install it first."

# Describe the problem

I noticed this problem today. The pipeline ran successfully on Jan 27th. I also don't see that a train-azure has been released. 

**Here is the contents of the inspec.yml:**

************************************
name: azure-resources
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '>= 4.6.9'
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
  platform: azure
************************************

**Here is the contents of the Gemfile:**

************************************
source 'https://rubygems.org'
gem 'inspec-bin'
gem 'inspec', '4.16.0'
************************************

**Here is the contents of the Dockerfile:**

************************************
FROM ruby:2.5
RUN gem install inspec-bin -v 4.16.0
RUN gem install inspec -v 4.16.0
RUN gem install activesupport -v 5.2.3
WORKDIR /usr/src/app
COPY . .
************************************

**Comment by valentinvsbg** [comment]
Hello,
I've hit the same problem with inspec `4.18.51`

**Comment by rmoles** [comment]
Hi @phenggeler thanks for submitting an issue. To help us further, could you please post a copy of the command that is being run to execute the profile. One issue I have noticed is that you are currently pointing at `master.tar.gz`. We would suggest pinning to a specific version and updating whenever necessary. Available versions can be found here: https://github.com/inspec/inspec-azure/releases

**Comment by clintoncwolfe** [comment]
The problem is in fact with train v3.2.15+; we are looking into it - thanks!

**Comment by valentinvsbg** [comment]
To workaround this you need to ensure train and train-core are version 3.2.14
https://rubygems.org/gems/train
https://rubygems.org/gems/train-core

**Comment by clintoncwolfe** [comment]
This was fixed in train 3.2.22, included in inspec 4.18.95.
