### ISSUE TITLE
No tags on resource_groups ?

### ISSUE THREAD

**Issue by rrey** [inspec/inspec-azure#236]
# Describe the problem

I've tried the solution provided here: https://github.com/inspec/inspec-azure/issues/138 to test tags on a resource_group;

with the following code:
```
control "main" do
  desc "Verifies that resource_group exists"

  describe azurerm_resource_groups.where(name: 'azrgr-app0-01') do
    it { should exist }

    tags = {
        :'ApplicationCode' => 'app0',
        :'ApplicationName' => 'app0',
    }
    its('tags.to_h') { should eq tags }
  end
end
```

But I have the following error:
```
  ×  main: Resource Groups with name == "azrgr-app0-01" (1 failed)
     ✔  Resource Groups with name == "azrgr-app0-01" is expected to exist
     ×  Resource Groups with name == "azrgr-app0-01" tags.to_h
     undefined method `tags' for Resource Groups with name == "azrgr-app0-01":#<Class:0x00007fe1e85cf1a8>
```

Am I missing something ?

**Comment by rrey** [comment]
Is the project still maintained ? I can see that the last issues from february had no response.

**Comment by rmoles** [comment]
Hi @rrey, based on our internal priorities, the current project state is "Maintained". However, this may change to "Active" in the not too distant future. 
We have been reviewing PR's and issues wherever possible. I will do my best to look into this issue whenever possible.

**Comment by rrey** [comment]
thanks for the feedback !

**Comment by rmoles** [comment]
@rrey some things for you to check in the meantime.
* Ensure you are pulling in the latest release of the resource pack in your inspec.yml: https://github.com/inspec/inspec-azure/releases
* Ensure you are using the latest version of inspec
* Run `inspec vendor --overwrite` or delete in the inspec lock before running the profile to ensure the resource pack has been pulled in for the inspec run.
Let me know if this solves your issue.

**Comment by rrey** [comment]
inspec (4.18.104)
Inspec-azure: 1.12.0

```
Profile: default
Version: (not specified)
Target:  azure://2a8ae5d7-02ef-4f90-8704-20aa8b8bdf87

  ×  main: Resource Groups with name == "azrgr-app0-01" (1 failed)
     ✔  Resource Groups with name == "azrgr-app0-01" is expected to exist
     ×  Resource Groups with name == "azrgr-app0-01" tags.to_h
     undefined method `tags' for Resource Groups with name == "azrgr-app0-01":#<Class:0x00007f8a88e924c8>


Profile: Azure Resource Pack (inspec-azure)
Version: 1.12.0
Target:  azure://2a8ae5d7-02ef-4f90-8704-20aa8b8bdf87

     No tests executed.

Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
```

**Comment by rmoles** [comment]
Hi @rrey, I've taken a look into this issue. It seems that the resource may need to be updated in order to support checking tags in this way. Currently, we are only registering the `name` column explicitly to be registered as an accessible method. https://github.com/inspec/inspec-azure/blob/master/libraries/azurerm_resource_groups.rb#L15
It is possible to access the tags field like so:
```
 azurerm_resource_groups.where(name: 'resource_group').get_column_values('tags')
```
Granted that's not the nicest of solutions as this will require it being split out into a separate test. The answer probably lies in updating the resource itself.

**Comment by rrey** [comment]
Ok, does it mean it will be fixed in the future ?

**Comment by rmoles** [comment]
Hi @rrey the latest resource pack release should fix your issue: https://github.com/inspec/inspec-azure/releases

**Comment by rrey** [comment]
Hi @rmoles, thx for the follow up !
I posted a review on https://github.com/inspec/inspec-azure/pull/238#pullrequestreview-395521870
I think there might be a copy/paste issue in the doc and potentially an issue.

**Comment by rrey** [comment]
reposting here the solution found by @rmoles that are working on v1.13.0 here:

1. Check for the full hash: 
```
its('tags')  { should include({"CreatedBy"=>"rmoles", "blah"=>"blah"....}) }
```

2. call the .first on the tags method
```
    its('tags.first')  { should include("CreatedBy"=>"rmoles") }
    its('tags.first')  { should include("tester"=>"test") }
output:

  ✔  azurerm_resource_groups: Resource Groups with name == "Inspec-Azure-rmoles"
     ✔  Resource Groups with name == "Inspec-Azure-rmoles" is expected to exist
     ✔  Resource Groups with name == "Inspec-Azure-rmoles" tags.first is expected to include {"CreatedBy" => "rmoles"}
     ✔  Resource Groups with name == "Inspec-Azure-rmoles" tags.first is expected to include {"tester" => "test"}
```
