### ISSUE TITLE
azurerm_network_security_group documentation

### ISSUE THREAD

**Issue by Sum123it** [inspec/inspec-azure#243]
Can you please give more elaborate documentation for azure network security resources?

E.g:
for aws security groups we have detailed description for functions:

'describe aws_security_group(group_name: my_group) do
  it { should allow_in(ipv4_range: ["10.1.2.0/24", "10.3.2.0/24"], protocol: 'all') }
end
describe aws_security_group(group_name: linux_servers) do
  it { should allow_in(port: 22, ipv4_range: '10.5.0.0/16') }
  it { should_not allow_in(port: 22, ipv4_range: '0.0.0.0/0') }
end
'
There is no inbound/outbound examples or port related check examples given for azure.
**Can you please include more elaborate examples for azure inspec resources? 
Or any guidance where do I find it? if any exists?**

**Comment by Sum123it** [comment]
@gsreynolds  - 
Can we go a step ahead with these features in `azure` as well like we have in `aws` with `ipv4 range` for `azurerm_network_security_group`?

```
describe aws_security_group(group_name: linux_servers) do
  it { should allow_in(port: 22, ipv4_range: '10.5.0.0/16') }
  it { should_not allow_in(port: 22, ipv4_range: '0.0.0.0/0') }
end
```
also below features:

```
inbound_rules
outbound_rules
```

**Comment by omerdemirok** [comment]
Please, see [here](https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_network_security_group.md) for how to use helper methods of `azure_network_security_group`.
