### ISSUE TITLE
Enhance azurerm_network_security_group to include relevant helper methods

### ISSUE THREAD

**Issue by skpaterson** [inspec/inspec-azure#249]
As per below comment, we should explore enhancing the security group resource with similar helper methods to the AWS resource pack:

https://github.com/inspec/inspec-azure/pull/248#issuecomment-640169056

**Comment by Sum123it** [comment]
Hello! Any updates on this?

**Comment by skpaterson** [comment]
Hi @Sum123it, @omerdemirok is working on some broader improvements to the Azure resource pack.  We'll try to pick this up at the same time.

**Comment by omerdemirok** [comment]
Please, see [here](https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_network_security_group.md) for how to use helper methods of `azure_network_security_group`.
