### ISSUE TITLE
Replace ActiveSupport

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec-azure#257]
This project introduces ActiveSupport into the Chef Workstation dependency set.

If it is only being used for XML parsing and could be replaced with rexml, we should do that.

We currently need to [pin ActiveSupport](https://github.com/inspec/train/commit/b79d4c2d420e8c14263cbff411672385db0034ca#diff-b87ab7fc919b5f707a5b409e31c504ef) to support older rubies - if CVEs are found that require us to update ActiveSupport we will be stuck.

**Comment by james-stocks** [comment]
It is preferred not to replace it with Nokogiri, by the way. That would need us to support compiling Nokogiri for all supported platforms and versions.

**Comment by sathish-progress** [comment]
ActiveSupport is a very rich library and provides us way more helper methods.. so I don't think we will be doing this anytime unless there is a very strong reason ..

**Comment by sathish-progress** [comment]
Closing this .. as there are no further discussion around the same ..
