### ISSUE TITLE
Enhance 'tags' feature for all the resources

### ISSUE THREAD

**Issue by Sum123it** [inspec/inspec-azure#262]
Need tags feature with interactive features like we have aws and gcp resources.

We should be able to do like this
```
describe any_azure_resource('resource') do
  its('tags_hash') { should include('Contact' => 'foo') }
  its('tags_hash') { should include('Contact') }                  # Regardsless of the value
end
```
also include below features:

`any_azure_resource.where(tags: /"created_by"=>/)`

**Comment by Sum123it** [comment]
@omerdemirok - Do we have an update on the major enhancements of Azure Pack?. Eagerly waiting!

**Comment by omerdemirok** [comment]
@Sum123it , hopefully next week, I'll put up a PR for that 🤞
