### ISSUE TITLE
nil:NilClass (NoMethodError)  on Inspec Version 4.22.0

### ISSUE THREAD

**Issue by rohancollab** [inspec/inspec-azure#270]
### 🌍Issue Description

Trying to run inspec exec using Inspec Version 4.22.0 and Inspec-Azure versions 1.18.4 and 1.18.3 results in 'for nil:NilClass (NoMethodError)'

### 🌍 InSpec and Platform Version

I am trying to run a simple azure verification test in docker through Gitlab pipeline.
Inspec version 4.22.0
Inspec-Azure version 1.18.4

**Details**

I am trying to run a simple azure verification test in docker through Gitlab pipeline.

I have created two profiles (one for inspec and the other for getting the azure dependencies (i.e the azure resource pack)). 
All my tests are in 'controls' folder in the 'Inspec-Azure/controls' directory
Azure inspec.yml is in the 'Inspec-Azure/Azure' directory 

My Directory structure is as follows

Inspec-AzureTests/
    Azure/
         ----- .gitkeep
          ----- inspec.yml
    controls/
          -----.gitkeep
          -----azure-verify.rb
    gitkeep
    inspec.yml

However the tests are failing with NilClass error as below

```
inspec exec "Inspec-AzureTests"
/usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:270:in `block in load_libraries': undefined method `[]=' for nil:NilClass (NoMethodError)

```
Here is my Inspec profile at this path 'Inspec-AzureTests/inspec.yml'

```
name: inspec-profile
title: inspec-profile
version: 1.0.0
depends:
  - name: azure-profile
    path: Azure
```
 
And my Azure profile at this path 'Inspec-AzureTests/Azure/inspec.yml'

```
name: azure-profile
title: My own Azure profile
version: 1.0.0
depends:
  - name: inspec-azure-name
    url: https://github.com/inspec/inspec-azure/archive/v1.18.4.tar.gz
```

I see that there was a similar issue that was resolved here-> https://github.com/inspec/inspec-azure/issues/201

So I also tried experimenting with various inspec and inspec-azure versions. Some of the combinations I tried are below 

inspec version 4.22 and inspec-azure version 1.18.4
inspec version 4.18.51 and inspec-azure version 1.10.0

All of them failing with the same Nil class error. Full stacktrace below

```
$ inspec exec "Inspec-AzureTests"
/usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:270:in `block in load_libraries': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:263:in `each'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:263:in `each_with_index'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:263:in `load_libraries'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/runner.rb:107:in `block in load'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/runner.rb:101:in `each'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/runner.rb:101:in `load'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/runner.rb:135:in `run'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/cli.rb:279:in `exec'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/base_cli.rb:35:in `start'
	from /usr/local/bundle/gems/inspec-bin-4.22.0/bin/inspec:11:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:23:in `load'
	from /usr/local/bundle/bin/inspec:23:in `<main>'
ERROR: Job failed: exit code 1

```

**Comment by omerdemirok** [comment]
Hi @rohancollab,
Can you try :
- Delete any `inspec.lock` files if exist.
- Add following into `Inspec-AzureTests/inspec.yml`
```
depends:
  - name: inspec-azure-name
    url: https://github.com/inspec/inspec-azure/archive/v1.18.4.tar.gz
``` 
- Run `inspec exec Inspec-AzureTests -t azure://` from the parent directory of `Inspec-AzureTests` (No quotation around the folder/profile name)

**Comment by rohancollab** [comment]
Hi @omerdemirok  Thanks for the reply. I did try that already a couple times but get this error

Unfortunately now my project has scrapped working with Azure  so cannot test it correctly as I do not have the tenantID and other details. However I tried the following and got a different error 

Command `inspec exec project/`

```
WARN: Skipping profile: 'inspec-azure' on unsupported platform: 'ubuntu/16.04'.

Profile: InSpec Profile (integrationqa)
Version: 0.1.0
Target:  local://

  ×  azure-webapp-verification: project/controls/azure.rb:1
     ×  Control Source Code Error integrationqa/controls/azure.rb:1 
     undefined method `azurerm_webapp' for #<Inspec::Rule:0x0000000005b6d640>


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped

```
I tried with various platform name and platform combinations (as below) but the same error (as above).
```
depends:
  - name: inspec-azure-name
    url: https://github.com/inspec/inspec-azure/archive/v1.18.4.tar.gz 
supports:
  - platform-name: ubuntu
    release: 16.04
  - platform: debian
  - platform: azure
```

I don't know if this is correct as I do not have the azure tenant details and all but looking at the error, I think it is being thrown even before inspec tries to connect to azure.

**Comment by omerdemirok** [comment]
@rohancollab 
You should use the -t switch. 
`inspec exec project -t azure://`

**Comment by rohancollab** [comment]
@omerdemirok  tried - no luck - Get an error  - Tenant id cannot be nil

```
root@rohan-VirtualBox:/home/rohan/inspectests# inspec exec project -t azure:// --chef-license accept
+---------------------------------------------+
✔ 1 product license accepted.
+---------------------------------------------+
Tenant id cannot be nil



```

**Comment by omerdemirok** [comment]
@rohancollab, has it been set as an environment variable?
see here: https://github.com/inspec/inspec-azure#inspec-for-azure

**Comment by rohancollab** [comment]
@omerdemirok  Thank you! That was the issue. It works now !
