### ISSUE TITLE
Bad URL is used when endpoint is set for non-default Azure Cloud

### ISSUE THREAD

**Issue by qiantaosap** [inspec/inspec-azure#289]
# Describe the problem
I set endpoint to 'azure_china_cloud' in order to try InSpec on Azure China, but the control fails due to REST API error.

`inspec exec` output as below: 
......
 Unsuccessful HTTP request to Azure REST API.
     HTTP 400.
     {:error=>"invalid_resource", :error_description=>"AADSTS500011: The resource principal named **https://management.chinacloudapi.cnsubscriptions** was not found in the tenant named 10f43eaa-0c68-461f-ba9e-0c5....

## Possible Solution

line 109 in libraries/backend/azure_environment.rb, the url should end with slash. Similar issues may exist for other non-default environments.

**Comment by omerdemirok** [comment]
@qiantaosap, can you update here after testing the new version of the resource pack `v1.22.1`?

**Comment by qiantaosap** [comment]
Hi @omerdemirok , the url issue is gone with v1.22.1. 
BTW, do you know the target date for inspec azure **v2.0**? README says 'azurerm_' resources don't support 'endpoint' setting and they will be deprecated in v2.0. However we are still using lots of 'azurerm_' resources in our controls, and might need to plan for migration accordingly. Thanks

**Comment by rmoles** [comment]
Hi @qiantaosap, as far as I know, there isn't a planned date for the azure resource pack to be updated to v2.0. @omerdemirok is currently working through adding a fully backward compatible version of each of the `azurerm_` resources that leverage the new generic resource. Ideally, it would be good to change to the new `azure_` resources, however the `azurerm_` resources should be available for the foreseeable future.

**Comment by qiantaosap** [comment]
@rmoles get it, thank you for the explanation!
