### ISSUE TITLE
need 'tags' for azure_storage_account

### ISSUE THREAD

**Issue by Sum123it** [inspec/inspec-azure#320]
Need to add `tags` for `azure_storage_account`

https://github.com/inspec/inspec-azure/blob/master/libraries/azurerm_storage_account.rb

failing with below:
```
 ×  tags
     undefined method `tags' for xxxxx1 Storage Account:#<Class:0x000000000882cde8>
     ×  tags
     undefined method `tags' for xxxx Storage Account:#<Class:0x000000000882cde8>
     ×  tags
```
  Inspec version `v1.32.0`

**Comment by tbugfinder** [comment]
Hi @Sum123it,
are you really using inspec v1.32.0 or is it rather inspec-azure 1.32.0 ?

**Comment by tbugfinder** [comment]
Did you look into the generic resource to access any property which is available within the API?
