### ISSUE TITLE
verify tags using azurerm_virtual_network

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec-azure#326]
### 🎛 Description

**Choose one:** is this a question (for now)

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

I'm using `azurerm_virtual_network` to test tags it got deployed with.
Using the documentation it would be `its('tags')` however the structure returned is of different type than plain json.
```
     expected: {"Name"=>"my-azure-vnet-test-default"}
          got: #<#<Class:0x00007fbfe12552f8>::AzureResourceProbe:0x00007fbfe2cfa680 @item={:Name=>"my-azure-vnet-test-default"}, @count=1>


```
- What should the right side of the test look like?
- After extracting the item itself ` using ` its('tags.item')`, I noticed that it's using symbolized JSON notation, which is IMHO less common. Not sure about best practice though or if it's just delivered by Azure API.

### 🌍 InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using

Inspec: 4.23.11
Platform: //github.com/inspec/inspec-azure/archive/v1.33.2.tar.gz

### 🤔 Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

Deploy VNET and run test.

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by omerdemirok** [comment]
@tbugfinder 
Thanks for opening this issue.
While we are working on that, you can use `include`:
```ruby
describe azure_virtual_network(resource_group: foo, name: bar) do
  its('tags') { should include("Name"=>"my-azure-vnet-test-default") }
  its('tags.count') { should cmp 1 }    # This will ensure that there is only one tag if this needs to be tested as well.
end
```
Note that: `azurerm_virtual_network` uses `azure_virtual_network` under the hood.

**Comment by tbugfinder** [comment]
Thank you!
Using `should include` indeed compares nicely.
Related to this kind of output I'm wondering how to deal with more complex (JSON) structures within `its()` properties, e.g. like those provided by the generic resource on a role definition which "seems" to be an array of a json structure.

**Comment by omerdemirok** [comment]
@tbugfinder, we can have a look if you provide an example.

**Comment by tbugfinder** [comment]
Well, 
I started off a sample repo (https://github.com/tbugfinder/kttfazure) showing the question with a custom_role however today I don't have luck with my code............

**Comment by tbugfinder** [comment]
Using the sample code base (https://github.com/tbugfinder/kttfazure/tree/issue_326_p1), I'm ending up with such kind of structures.
```
control 'generictest_id' do
  describe azure_generic_resource(resource_id: role_id) do
    it { should exist }
    its('properties.permissions')         { should include 'Actions' }
    its('properties.permissions.actions') { should include 'WhichAreTheProperties' } #  undefined method `actions' for #<Array:0x00007f2ea11f68d8>
  end
end
```
What's best to deal with those?

     expected [#<#<Class:0x00007f40f1413a00>::AzureResourceProbe:0x00007f40f11f1768 @item={:actions => ["*"], :notActions => [], :dataActions => [], :notDataActions => []}, @count=4>] to include "Actions"
     Diff:
     @@ -1 +1 @@
     -["Actions"]
     +[#<#<Class:0x00007f40f1413a00>::AzureResourceProbe:0x00007f40f11f1768 @item={:actions=>["*"], :notActions=>[], :dataActions=>[], :notDataActions=>[]}, @count=4>]

**Comment by omerdemirok** [comment]
@tbugfinder:
As the error message says, you should look for `actions` not `Actions`:
```
 [#<#<Class:0x00007f40f1413a00>::AzureResourceProbe:0x00007f40f11f1768 @item={:actions => ["*"], :notActions => [], :dataActions => [], :notDataActions => []}, @count=4>] to include "Actions"
```

Looks like `properties.permissions` is an array, hence the error: 
```
undefined method `actions' for #<Array:0x00007f2ea11f68d8>
```

Please read the Azure docs (REST API) of the resource you want to test and check the data types.

**Comment by tbugfinder** [comment]
@omerdemirok 
Thanks for the update.

I've already found in a few examples use of pattern like `its('properties.permissions.first.<...>')`.
So how would I iterate on all items within the permissions array (https://docs.microsoft.com/en-us/rest/api/authorization/roledefinitions/get) while using its('properties.permissions')?

**Comment by omerdemirok** [comment]
First of all, I recommend you to have a look at the static resources created for role definitions:
https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_role_definition.md
https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_role_definitions.md

If it doesn't answer your request, then, you can try this:
```
actions = azure_role_definition(resource_id: "/foo/bar").properties.permissions.select { |e| e.respond_to?(:actions) }.first.actions

describe actions do
   it { should include("Microsoft.ContainerRegistry/registries/pull/read") }  
 end 
```
