### ISSUE TITLE
Q / Error: can't modify frozen String while using "old" azurerm_* resources

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec-azure#333]
### 🎛 Description

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

Hi,
we've upgraded from inspecv3 to inspecv4 and also bumped up inspec-azure profile. While running inspec within our CI system and using azurerm_* resources those fail with such an error:

```
2:04:13  Profile: default
2:04:13  Version: (not specified)
2:04:13  Target:  azure://****
2:04:13  
2:04:13    ×  default: Test Suite: 'default'
2:04:13       ×  Control Source Code Error /tmp/code/test/integration/default/controls/default.rb:35 
2:04:13       can't modify frozen String
2:04:13  
2:04:13  
2:04:13  Profile: Azure Resource Pack (inspec-azure)
2:04:13  Version: 1.35.0
2:04:13  Target:  azure://****
2:04:13  
2:04:13       No tests executed.
2:04:13  
2:04:13  Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
2:04:13  Test Summary: 0 successful, 1 failure, 0 skipped
```
I'm wondering how to dig into getting the root cause of failing of the backwards compatible resource.

### 🌍 InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using

inspec 4.23.11
inspec-azure 1.35.0

### 🤔 Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

"not sure what's different within the CI system" compared to the develoment server which doesn't show this error.

bundle exec inspec exec ....

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

How could such be created?

**Comment by omerdemirok** [comment]
@tbugfinder,
First, can you delete inspec.lock file and try again.
If it doesn't work, can you share:
- inspec.yml,
- inspec control giving the error?

**Comment by tbugfinder** [comment]
thank you.
Source is pulled off git repo without inspec.lock.
```
name: default
supports:
- platform: azure
depends:
- name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/v1.35.0.tar.gz
```

The stripped control which raises the error (only in CI) is:
```
control 'default' do
  impact 1.0
  title  "Test Suite: 'default'"
  desc   "This test suite asserts the correct functionality of the stack under test."
  tag    name

  describe azurerm_resource_groups.where(name: rgname) do
    it { should exist }
  end
end
```

Changing to azure_resource_groups finishes successfully.

**Comment by omerdemirok** [comment]
azurerm_resource_groups uses the new azure_resource_groups under the hood. They should act the same. If it only happens in CI, I suggest you to check the incpec.yml. You need to see a deprecation message if it is the new resource being used.

In your control, you can use the singular resource which will run faster and allow more granular testing. 
azure_resource_group : https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_resource_group.md

**Comment by tbugfinder** [comment]
Hm, the code is loaded of git so DEV and CI are identical in regards to that, however CI doesn't have the DEPRECATION warning.

Sounds like I need more DEBUG output.

DevEnv:
```
$$$$$$ Verifying the systems...
$$$$$$ Verifying the 'azure' system...
DEPRECATION: `azurerm_resource_groups` uses the new resource `azure_resource_groups` under the hood. azurerm_resource_groups will be deprecated soon and it is advised to switch to the fully backward compatible new resource. Please see the documentation for the additional features available.

Profile: default
Version: (not specified)
Target:  azure://
```


CIEnv:
```
$$$$$$ Verifying the systems...
$$$$$$ Verifying the 'azure' system...
 
Profile: default
Version: (not specified)
Target:  azure://****

  ×  default: Test Suite: 'default'
     ×  Control Source Code Error /tmp/code/integration/default/controls/default.rb:xx
     can't modify frozen String
```

**Comment by tbugfinder** [comment]
@omerdemirok 
so there error is only raised within CI+kitchen, not sure if kitchen fails to properly load the azurerm_* dependencies.

**Comment by tbugfinder** [comment]
I've enabled RUBYOPT=''--debug=frozen-string-literal".

This line is reported as raising the error:
https://github.com/inspec/inspec-azure/blob/v1.33.2/libraries/backend/helpers.rb#L332

```
 can't modify frozen String, created at libraries/backend/helpers.rb:332
```

**Comment by omerdemirok** [comment]
Thanks for that @tbugfinder.
There is no string manipulation in this line. It is interesting to raise this error.
CI tests are working fine on my end. Since we can't replicate the issue, it is risky to do any changes.
I suggest you ensure that your dev env and CI env are identical.
I'll keep trying to replicate it meanwhile.

**Comment by tbugfinder** [comment]
Using inspec-azure 0.19.7 it doesn't fail - obviously.
```
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.19.7
 Target:  azure://****
```

**Comment by tbugfinder** [comment]
`1.20.0` is ok.
```
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Resource Groups with name start_with? "InSpec" is expected to exist
      expected Resource Groups with name start_with? "InSpec" to exist
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.20.0
 Target:  azure://****
 
      No tests executed.

```

**Comment by tbugfinder** [comment]
```
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Resource Groups with name start_with? "InSpec" is expected to exist
      expected Resource Groups with name start_with? "InSpec" to exist
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.26.3
 Target:  azure://****
 
      No tests executed.
```

**Comment by tbugfinder** [comment]
```
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Control Source Code Error /var/jenkins_home/workspace/tests/ci/blueprint-azure-resource-group/test/integration/default/controls/default.rb:17 
      can't modify frozen String, created at libraries/backend/helpers.rb:330
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.29.0
 Target:  azure://****
 
      No tests executed.
```

**Comment by tbugfinder** [comment]
```
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Resource Groups with name start_with? "InSpec" is expected to exist
      expected Resource Groups with name start_with? "InSpec" to exist
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.27.1
 Target:  azure://****
 
      No tests executed.
```

**Comment by tbugfinder** [comment]
So here is the version which first raises this error in my CI environment.
```
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Control Source Code Error /var/jenkins_home/workspace/tests/ci/blueprint-azure-resource-group/test/integration/default/controls/default.rb:17 
      can't modify frozen String, created at libraries/backend/helpers.rb:330
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.28.0
 Target:  azure://****
 
      No tests executed.
```

**Comment by tbugfinder** [comment]
Actually that's not surprising as 1.28.0 adds the given resource to inspec-azure.
https://github.com/inspec/inspec-azure/pull/301/files

**Comment by tbugfinder** [comment]
Would more files in libraries require header tag `# frozen_string_literal: true`?

**Comment by tbugfinder** [comment]
After adding `.dup` to line: https://github.com/inspec/inspec-azure/blob/v1.37.0/libraries/azure_resource_groups.rb#L76

CI system is happy:
```
 DEPRECATION: `azurerm_resource_groups` uses the new resource `azure_resource_groups` under the hood. azurerm_resource_groups will be deprecated soon and it is advised to switch to the fully backward compatible new resource. Please see the documentation for the additional features available.
 
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Azure Resource Groups - api_version: 2020-07-01 latest /resourcegroups/ /resourcegroups/ with name start_with? "InSpec" is expected to exist
      expected Azure Resource Groups - api_version: 2020-07-01 latest /resourcegroups/ /resourcegroups/ with name start_with? "InSpec" to exist
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.37.0
 Target:  azure://****
 
      No tests executed.
 
 Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
 Test Summary: 0 successful, 1 failure, 0 skipped
```

**Comment by tbugfinder** [comment]
or add `.dup` at the end of the source frozen string.
https://github.com/inspec/inspec-azure/blob/master/libraries/backend/helpers.rb#L340-L342

**Comment by tbugfinder** [comment]
Ok,
using debug I'm ending up in
```
Exception `FrozenError' at /.../vendor/bundle/ruby/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/logger.rb:300 - can't modify frozen String, created at libraries/backend/helpers.rb:340
```

logger.rb:300 is:
`msg.concat("\n")`


Using `inspec` CLI inspec-azure is ok however using kitchen as verifier raises this error.

**Comment by tbugfinder** [comment]
I'm closing this issue here as a fix made it into test-kitchen.
https://github.com/test-kitchen/test-kitchen/pull/1731
