### ISSUE TITLE
Undefined Method azure_key_vault

### ISSUE THREAD

**Issue by ElAouaneHamza** [inspec/inspec-azure#366]
Hello guys, so sorry to bother and I do apologise if this is the wrong section. I am so frustrated because I don't know how to solve this issue. 
When I run the command inspec exec on any resource, I got the error `undefined method`
# Describe the problem

I installed chef, Inspec,ruby, and gem and all the dependecies required. In my Azure portal I created a service principal and set those credential under `/.azure/credentials`. But when I run `inspect exec . -t azure://` I got the following error:

```
×  azure-rg-test: Checks my demo rg
     ×  Control Source Code Error ./example.rb:3 
     undefined method `azure_key_vault' for #<Inspec::Rule:0x00007f88d548c780>
```
And I don't know what I am doing wrong and couldn't find anything online related to this issue and I don't know if a configuration error or a operative system error(I am on a Mac).

Thank you very much for you time and help

**Comment by sathish-progress** [comment]
are you using the latest version of `inspec-azure`?

**Comment by kitforbes** [comment]
Getting the same error with inspec v4.36.4 and inspec-azure v1.49.1.
```
C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:741:in `method_missing': `azure_key_vault` is not available on an example group (e.g. a `describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). (RSpec::Core::ExampleGroup::WrongScopeError)
```

**Comment by sathish-progress** [comment]
possibly because of the old dependency cache.. 
try this `inspec vendor --overwrite` 
keep posted on how it goes ..

**Comment by sathish-progress** [comment]
Since we have no update .. I assume this is closed .. please re-open if you have still face this ..

**Comment by kitforbes** [comment]
Sorry for the long delay in replying. I just wanted to update with what I was doing wrong - which may help others in the future.

Essentially I was trying to do this:
```ruby
describe azure_key_vaults(resource_group: 'some-rg').ids.each do |id|
  describe azure_key_vault(resource_id: id) do
    it { should exist }
  end
end
```
but it should be written like this:
```ruby
azure_key_vaults(resource_group: 'some-rg').ids.each do |id|
  describe azure_key_vault(resource_id: id) do
    it { should exist }
  end
end
```
The reason I was attempting to use a second `describe` was for neatness in the output, but that was just me using the tool incorrectly.
