### ISSUE TITLE
azure_resource_group's resource_id  expected format is incorrect

### ISSUE THREAD

**Issue by teddyross** [inspec/inspec-azure#369]
# Overview
The format for azure_resource_group's resource_id argument doesn't seem to work as expected.

# Problem Description
According to the documentation found here:
https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_resource_group.md

azure_resource_group's resource_id argument requires the format:
```
'/{subscriptionId}/resourcegroups/{resourceGroupName}'
```

However, when that format is supplied an error is received:
```
     [FAIL]  Control Source Code Error ./my-test/controls/my-test.rb:5
     Resource URI should be in the format of /subscriptions/{subscription_id}/resourceGroups/{resource_group}/providers/Microsoft.Compute/virtualMachines/{resource_name}. Found: /bebebebe-e7e7-b2b2-b3b3-111111111111/resourcegroups/MyResourceGroup
```

The documentation says we should use this:
```
'/{subscriptionId}/resourcegroups/{resourceGroupName}'
```

but the code incorrectly requires this:
```
'/subscriptions/{subscription_id}/resourceGroups/{resource_group}/providers/Microsoft.Compute/virtualMachines/{resource_name}'
```

# Environment
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

Chef Workstation version: 21.3.346
Chef Infra Client version: 16.11.7
Chef InSpec version: 4.29.3
Chef CLI version: 3.1.3
Chef Habitat version: 1.6.267
Test Kitchen version: 2.11.2
Cookstyle version: 7.10.0

**Comment by sa-progress** [comment]
There was issue with document .Have updated the same.
