### ISSUE TITLE
Azure Active Directory Domain Services - PQ3

### ISSUE THREAD

**Issue by ppradhan9** [inspec/inspec-azure#390]
Resource Support for Azure Active Directory Domain Services
Coverage:
1.Dev
2.Test
3.Documentation

**Comment by sathish-progress** [comment]
plural - https://docs.microsoft.com/en-us/graph/api/domain-list?view=graph-rest-1.0&tabs=http
singular - https://docs.microsoft.com/en-us/graph/api/domain-get?view=graph-rest-1.0&tabs=http
