### ISSUE TITLE
uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState

### ISSUE THREAD

**Issue by jnahelou** [inspec/inspec-azure#592]
Inspec crash due to missing import in active support while using inspec-azure.

## How to reproduce
```bash
$ bundle exec inspec version
4.52.9

$ bundle exec gem list | grep activesupport
activesupport (7.0.0)

$ cat inspec.yml
---
name: default-profile
title: InSpec Profile
maintainer: jnahelou
copyright: jnahelou
copyright_email: jnahelou
license: Apache-2.0
summary: InSpec Compliance Profile
version: 0.1.0
description: Default test configuration
inspec_version: ">= 2.3.5"
depends:
- name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/main.tar.gz

$ bundle exec inspec check inspec.yml
<crash with stacktrace>
vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:185:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
```

I found [here](https://github.com/rails/rails/pull/43852#issuecomment-992674343)  that they moved to autoload but in inspec-azure, the autoload seems not triggered in requirements:

https://github.com/inspec/inspec-azure/blob/642b6ac749efd11a179f7793283c1d1bd457181b/libraries/backend/azure_require.rb#L8

**Comment by jnahelou** [comment]
As a workaround, I switch locally in `libraries/backend/azure_require.rb`

```diff
-require 'active_support/core_ext/hash'
+#require 'active_support/core_ext/hash'
+require 'active_support'
```

and `inspec.yml`

```yaml
depends:
- name: inspec-azure
  path: /home/jnahelou/perso/inspec-azure
```

**Comment by jnikles1** [comment]
I ran into this issue as well. Thanks for mentioning the workaround

**Comment by YohanValette-DXC** [comment]
I also ran into this problem.

I am running kitchen in a vscode devcontainer

```
Dockerfile
ARG VARIANT=2-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/ruby:0-${VARIANT}

ENV KITCHEN_TF_VERSION='6.0.0'
ENV KITCHEN_SSH_VERSION='1.0.3'

...

RUN gem install \
        kitchen-terraform:${KITCHEN_TF_VERSION} \
        kitchen-ssh:${KITCHEN_SSH_VERSION}
```

It is not a solution for me to locally clone the inspec-azure repo.
Is there a fix planned ?

**Comment by DesislavaNPetrova** [comment]
I ran into this issue as well. Any updates on the fix?

**Comment by sathish-progress** [comment]
investigating the issue, a fix should be pushed by EOW.

**Comment by sathish-progress** [comment]
will be fixed as part of https://github.com/inspec/inspec-azure/pull/608
