### ISSUE TITLE
Add Availability section to each resource docs

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-azure#64]
A section should be added indicating that the resource is available via a resource pack, how to install, and what version the resource was first available.

**Comment by TrevorBramble** [comment]
@clintoncwolfe Sorry, this is unclear to me. Do you mean each of [these files](https://github.com/inspec/inspec-azure/tree/master/docs/resources) should have a new section? Do you have an example of this we could follow?

**Comment by clintoncwolfe** [comment]
Yes, each doc file should have an Availability section (so that when it is rendered on the main website, it's clear you need to treat it as a resource pack).

I give a proposed example here: https://github.com/inspec/inspec/pull/3184#issuecomment-401823322

**Comment by clintoncwolfe** [comment]
And I'm happy to volunteer to do this work; I've been playing with some Markdown parser-generators.
