### ISSUE TITLE
README implies Terraform is required

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-azure#72]
As this project moves from a development project to a user-facing repository of resources, we need to make sure the README makes sense to multiple audiences.  One confusing point to me was the matter of Terraform and Direnv; if I were a user with an existing Azure infra I wanted to test, would I need to setup Terraform, manage workspaces, remote state, etc?

**Comment by dmccown** [comment]
I can get this clarified. Terraform and Direnv are only required to run integration tests (useful if you plan to contribute). Otherwise you may use whatever you like. I'll get a PR with an updated README.
