### ISSUE TITLE
Resources need to be prefixed `azurerm`

### ISSUE THREAD

**Issue by Padgett** [inspec/inspec-azure#81]
Currently resources are mixed between `azure` and `azurerm` prefixes. Standardize on `azurerm` and alias `azure` with a deprecation warning.
Be sure to update integration tests and documentation.

- [x] azure_monitor_activity_log_alert
- [x] azure_monitor_activity_log_alerts
- [x] azure_monitor_log_profile
- [x] azure_monitor_log_profiles
- [x] azure_network_security_group
- [x] azure_network_security_groups
- [x] azure_network_watcher
- [x] azure_network_watchers
- [x] azure_resource_groups
- [x] azure_security_center_policies
- [x] azure_security_center_policy

**Comment by Padgett** [comment]
I'll snag network_watcher(s) and network_security_group(s) for starters

**Comment by TrevorBramble** [comment]
I'll get resource groups and security center polic{y|ies}

**Comment by Padgett** [comment]
Looks like that leaves activity_log_alert(s), I'll do those next

**Comment by Padgett** [comment]
Starting monitor_log_profile(s)

**Comment by Padgett** [comment]
@clintoncwolfe The naming scheme follows Azure's with v1 being `azure` and v2 being `azurerm` which also matches the Terraform providers.

**Comment by Padgett** [comment]
Resolved
