### ISSUE TITLE
No Graph API access prevents terraform from running

### ISSUE THREAD

**Issue by dmccown** [inspec/inspec-azure#99]
# Description of Issue

If you attempt to start a Terraform environment without having permissions to the Graph API your Terraform task will fail with an error "Insufficient Permissions".  We should make Graph an optional configuration item so someone is not blocked if they don't have permissions while developing new resources.

At the moment we have optional features in Terraform:
- msi_vm
- network_watcher

What would be a good interface to allow someone to opt into additional components depending on what they are testing without needing a huge rake command.

If we were to follow the existing pattern we would have something like:
```
$ rake network_watcher graph tf:apply test:integration
```
### Consolidated rake task
```
$ rake with[network_watcher,graph,msi_vm,etc] # modifies .envrc
$ source .envrc # or direnv allow
$ rake tf:apply
$ rake test:integration
$ rake with[] # modifies .envrc to remove all optional components
$ source .envrc # or direnv allow
```
This task could modify your `.envrc` file to add any optional components to your configuration. We could then output something on other rake tasks to output which optional components you are using. As well as noting that tests will be skipped for any optional components you aren't using.

By default all optional components would be disabled. 

### Other ideas

Are there other ideas that would be a better user experience and provide clarity around what components you have enabled/disabled?

**Comment by TrevorBramble** [comment]
I think your proposal is reasonable and provides a fine user experience, particularly by defaulting to off.

Should we do something to surface the status of those things? Print them at the start of a run?
